---
title: "Reproducible documents, presentations, and websites with Quarto"
author: "Hunter Glanz, Emily Robinson & Allison Theobold"
subtitle: "USCOTS 2023"
---

# Welcome

  - Welcome to the Julia workshop for Data Science!
  - The goal for the workshop is to highlight the main features that make Julia an attractive option for data science programmers
  - The workshop is intended for any data scientist with experience in R and/or python who is interested in learning the attractive features of Julia for Data Science. No knowledge of Julia is required.
  - Workshop materials in the github repository [julia-workshop](https://github.com/crsl4/julia-workshop)

## Learning Objectives for Tutorial

At the end of the tutorial, participants will be able to:

  - Identify the main features that make Julia an attractive language for Data Science
  - Set up a Julia environment to run their data analysis
  - Efficiently handle datasets (even across different languages) through Tables.jl and Arrow.jl
  - Fit (generalized) linear mixed models with MixedModels.jl
  - Communicate across languages (Julia, R, python)

Intended audience and level:

This workshop is intended for individuals familiar with RMarkdown and RStudio who are interested in learning more about Quarto! While we will not be coding in R during the workshop, it could be useful for individuals to have some familiarity with programming in R. 

# Schedule

| Time          | Topic                                                                         | Presenter                    |
|:-------------------:|:-----------------------------------------------------------------------------:|:----------------------------:|
| 8:30 - 8:45 | Introductions, workshop outline, distribute materials                           |                   |
| 8:45 - 9:00 | A brief refresher of RStudio                                                    |                   |
| 9:00 - 9:30 | Hello Quarto                                                                    | Allison Theobold  |
| 9:30 - 10:00 | Activity: Exploring YAML options                                               | You!              |
| 10:00 - 10:30 | Snack break!                                                                  |                   |
| 10:30 - 10:45 | Share what you discovered!                                                    | You!              |
| 10:45 - 11:30 | Embellishing Quarto documents                                                 | Emily Robinson    |
| 11:30 - 12:00 | Activity: Try it out!                                                         | You!              |
| 12:00 - 1:00  | Lunch break!                                                                  |                   |
| 1:00 - 1:30   | Quarto presentations                                                          | Allison Theobold  |
| 1:30 - 1:45   | Activity: Make a simple presentation                                          | You!              |
| 1:45 - 2:30   | Styling Quarto presentations                                                  | Emily Robinson    |
| 2:30 - 3:00   | Snack break!                                                                  |                   |
| 3:00 - 3:30   | Activity: Try it out!                                                         | You!              |
| 3:30 - 3:45   | A brief introduction to version control                                       | Hunter Glanz      |
| 3:45 - 4:00   | Publishing content with GitHub pages                                          | Emily Robinson    |
| 4:00 - 4:30   | Quarto websites                                                               | Allison Theobold  |

# In preparation for the workshop

Participants are required to follow the next steps before the day of the workshop:

 1. Git clone the workshop repository: `git clone https://github.com/crsl4/julia-workshop.git`

 2. Install Julia. The recommended option is to use [JuliaUp](https://github.com/JuliaLang/juliaup):

  - Windows: `winget install julia -s msstore`

  - Mac and Linux: `curl -fsSL https://install.julialang.org | sh`
  - Homebrew users: `brew install juliaup`